# Test 2024-07-04 at 22:23:09

name: Test

on:
  push:
    paths:
      - '**/main.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Install gcc
      run:
        sudo apt install build-essential

    - name: Run putChar
      run: |
        gcc -Wall -Wextra putChar.c && ./a.out
